### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items' 

### ISSUE THREAD

**Issue by animesh-007** [SysCV/qdtrack#107]
```
python tools/to_bdd100k.py /workspace/project/working/qdtrack/configs/bdd100k/qdtrack-frcnn_r50_fpn_12e_bdd100k.py --res ./result.pkl --task box_track --bdd-dir ./result
loading annotations into memory...
Done (t=7.71s)
creating index...
index created!

Loading results from ./result.pkl

Start converting to BDD100K box tracking format
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "tools/to_bdd100k.py", line 72, in <module>
    main()
  File "tools/to_bdd100k.py", line 69, in main
    dataset, results, args.task, out_base=args.bdd_dir, nproc=args.nproc)
  File "/workspace/project/working/qdtrack/qdtrack/core/to_bdd100k/transforms.py", line 139, in preds2bdd100k
    metric2func[task](dataset, results, out_base, *args, **kwargs)
  File "/workspace/project/working/qdtrack/qdtrack/core/to_bdd100k/transforms.py", line 101, in box_track_to_bdd100k
    for id_, instance in track_dict.items():
AttributeError: 'list' object has no attribute 'items'
```

I was trying to convert the output prediction file to Scalabel format for the bdd100k dataset but I am facing the following issue.

**Comment by Yuchy-Zhao** [comment]
I meet the same problem. How do you solve it?

**Comment by Raspberry-beans** [comment]
Hi,
I am dealing with same issue. Kindly share if anyone has a solution.
