### ISSUE TITLE
Problem while converting BDD tracking dataset. KeyError: "video_name"

### ISSUE THREAD

**Issue by amancodeblast** [SysCV/qdtrack#54]
(qdtrack) user1@king-MS-7B48:~/quasi/qdtrack$ python -m bdd100k.label.to_coco -m track -i bdd100k/labels/box_track_20/train -o data/bdd/labels/box_track_20/box_track_train_cocofmt.json
[2021-07-13 01:25:32,075 to_coco.py:305 main] Mode: track
remove-ignore: False
ignore-as-class: False
[2021-07-13 01:25:32,075 to_coco.py:307 main] Loading annotations...
[2021-07-13 01:30:06,229 to_coco.py:318 main] Converting annotations...
  0%|                                                  | 0/1400 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/iiitd/anaconda3/envs/qdtrack/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/iiitd/anaconda3/envs/qdtrack/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/iiitd/anaconda3/envs/qdtrack/lib/python3.7/site-packages/bdd100k-1.0.0-py3.7.egg/bdd100k/label/to_coco.py", line 337, in <module>
    main()
  File "/home/iiitd/anaconda3/envs/qdtrack/lib/python3.7/site-packages/bdd100k-1.0.0-py3.7.egg/bdd100k/label/to_coco.py", line 327, in main
    labels, args.ignore_as_class, args.remove_ignore
  File "/home/iiitd/anaconda3/envs/qdtrack/lib/python3.7/site-packages/bdd100k-1.0.0-py3.7.egg/bdd100k/label/to_coco.py", line 227, in bdd100k2coco_track
    video = dict(id=video_id, name=video_anns[0]["video_name"])
KeyError: 'video_name'

The directory structure for the BDD  Dataset 
Image--|--100k - Train, test, valid folders each containing images
             |--track - train, test, valid folder containing folders, each folder, for a sequence of images
             | 

Labels--|--det_20 - train, valid json files
             |--box_track_20  - train, val folder containing .json files corresponding to each folder containing a secqence of image. 
             |
There is also an issue{[#53](https://github.com/SysCV/qdtrack/issues/53)} while converting the detection dataset. Please let me know if there is any more information that is required in order to help.

**Comment by iAmJuan550** [comment]
I'm getting the same error. Did you find a solution to this?

**Comment by XiaLiPKU** [comment]
Hi,

We no longer provide the coco-format jsons.
Instead, we provide the scripts to convert bdd100k format to coco format.
You may refer this part: https://github.com/SysCV/qdtrack/blob/master/docs/GET_STARTED.md#convert-annotations

**Comment by LisaBernhardt** [comment]
Maybe this post helps: Issue{[#28](https://github.com/SysCV/qdtrack/issues/28)}
