### ISSUE TITLE
Your code doesn't work. I get error: TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by iAmJuan550** [SysCV/qdtrack#60]
your code doesn't work, I get the following error:

```
Traceback (most recent call last):
  File "/home/muhammadmehdi/PycharmProjects/memex/qdtrack_test.py", line 3, in <module>
    from qdtrack.apis import multi_gpu_test, single_gpu_test
  File "/home/muhammadmehdi/PycharmProjects/memex/qdtrack/qdtrack/apis/__init__.py", line 1, in <module>
    from .inference import inference_model, init_model
  File "/home/muhammadmehdi/PycharmProjects/memex/qdtrack/qdtrack/apis/inference.py", line 11, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/mmdet/datasets/__init__.py", line 11, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/mmdet/datasets/utils.py", line 9, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/mmdet/models/__init__.py", line 6, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/mmdet/models/dense_heads/__init__.py", line 4, in <module>
    from .autoassign_head import AutoAssignHead
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/mmdet/models/dense_heads/autoassign_head.py", line 12, in <module>
    from mmdet.models.dense_heads.paa_head import levels_to_images
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/mmdet/models/dense_heads/paa_head.py", line 12, in <module>
    import sklearn.mixture as skm
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 13, in <module>
    from .validation import (as_float_array,
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 27, in <module>
    from ..utils._joblib import Memory
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/utils/_joblib.py", line 18, in <module>
    from ..externals.joblib import __all__   # noqa
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/externals/joblib/parallel.py", line 32, in <module>
    from .externals.cloudpickle import dumps, loads
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 151, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/muhammadmehdi/PycharmProjects/memex/venv/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 132, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
```
The code that causes this:
```
import torch
from mmcv import Config
from qdtrack.apis import multi_gpu_test, single_gpu_test
from qdtrack.models import build_model
from qdtrack.datasets import build_dataloader

cfg = Config.fromfile('configs/qdtrack-frcnn_r50_fpn_12e_bdd100k.py')
torch.backends.cudnn.benchmark = True
cfg.model.pretrained = None
cfg.data.test.test_mode = True
```

**Comment by iAmJuan550** [comment]
I fixed the problem by using python 3.7 instead
