### ISSUE TITLE
Quasi Dense Faster RCNN: 'NoneType' object has no attribute 'rpn' when using pretrained model with TAO

### ISSUE THREAD

**Issue by iAmJuan550** [SysCV/qdtrack#64]
I am trying to test your pretrained model from the TAO dataset and this is the error I am getting:
```
100%|██████████| 1/1 [00:00<00:00, 1535.81it/s]
Traceback (most recent call last):
  File "/home/muhammadmehdi/PycharmProjects/memex/SysCV-qdtrack/mmcv/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/muhammadmehdi/PycharmProjects/memex/SysCV-qdtrack/qdtrack/models/mot/quasi_dense.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "/home/muhammadmehdi/PycharmProjects/memex/SysCV-qdtrack/mmdetection/mmdet/models/detectors/two_stage.py", line 39, in __init__
    rpn_head_.update(train_cfg=rpn_train_cfg, test_cfg=test_cfg.rpn)
AttributeError: 'NoneType' object has no attribute 'rpn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/muhammadmehdi/PycharmProjects/memex/run_offline.py", line 56, in <module>
    root_dir, {})
  File "/home/muhammadmehdi/PycharmProjects/memex/algorithm.py", line 579, in run_auto
    model = build_model(cfg.model, train_cfg=None, test_cfg=None)
  File "/home/muhammadmehdi/PycharmProjects/memex/SysCV-qdtrack/qdtrack/models/builder.py", line 15, in build_model
    return build(cfg, MODELS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/muhammadmehdi/PycharmProjects/memex/SysCV-qdtrack/mmcv/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/muhammadmehdi/PycharmProjects/memex/SysCV-qdtrack/mmcv/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: QuasiDenseFasterRCNN: 'NoneType' object has no attribute 'rpn'
```

The code:
```
cfg = Config.fromfile('configs/tao/qdtrack_frcnn_r101_fpn_24e_lvis.py')

# set cudnn_benchmark
torch.backends.cudnn.benchmark = True
cfg.model.pretrained = None
cfg.data.test.test_mode = True

# build the model and load checkpoint
model = build_model(cfg.model, train_cfg=None, test_cfg=None)
checkpoint = load_checkpoint(model, 'weights/qdtrack_tao.pth', map_location='cuda')
```

**Comment by iAmJuan550** [comment]
I solved this problem by using `model = build_model(cfg.model, train_cfg=None, test_cfg=cfg.get('test_cfg'))`
