### ISSUE TITLE
KeyError: 'QDTrack is not in the model registry'

### ISSUE THREAD

**Issue by iAmJuan550** [SysCV/qdtrack#75]
Your code no longer works. I tried the following:

```
cfg = Config.fromfile('configs/tao/qdtrack_frcnn_r101_fpn_24e_lvis.py')

# set cudnn_benchmark
torch.backends.cudnn.benchmark = True
cfg.model.pretrained = None
cfg.data.test.test_mode = True

# build the model and load checkpoint
model = build_model(cfg.model, train_cfg=None, test_cfg=cfg.get('test_cfg'))
```

The error:

```
Traceback (most recent call last):
  File "/home/muhammadmehdi/PycharmProjects/memex/run_offline.py", line 109, in <module>
    auto_estimated_ellipsoids = run_auto(auto_img_files, auto_ptcld_files, auto_pose_files, auto_int_files, root_dir)
  File "/home/muhammadmehdi/PycharmProjects/memex/algorithm.py", line 275, in run_auto
    model = build_model(cfg.model, train_cfg=None, test_cfg=cfg.get('test_cfg'))
  File "/home/muhammadmehdi/PycharmProjects/memex/SysCV-qdtrack/qdtrack/models/builder.py", line 15, in build_model
    return build(cfg, MODELS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/muhammadmehdi/PycharmProjects/memex/SysCV-qdtrack/mmcv/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/muhammadmehdi/PycharmProjects/memex/SysCV-qdtrack/mmcv/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'QDTrack is not in the model registry'

Process finished with exit code 1
```

**Comment by iAmJuan550** [comment]
I solved the problem by reinstalling qdtrack again:

```
git clone https://github.com/SysCV/qdtrack.git SysCV-qdtrack
cd SysCV-qdtrack
# install mmcv 1.3.10 from source
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
# go to mmcv/version.py and change __version__ to 1.3.10
MMCV_WITH_OPS=1 pip install -e .
cd ..
# install mmdet 2.14.0
pip install openmim
mim install mmdet==2.14.0
# install qdtrack
python setup.py develop
```
